name: todo_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  intl: ^0.18.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^16.1.0
  flutter_timezone: ^1.0.8
  rxdart: ^0.27.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
